map_resolution: 0.1
map_size: 512
map_start_x: 0.5
map_start_y: 0.5
map_multi_res_levels: 2
update_factor_free: 0.4
update_factor_occupied: 0.9 
map_update_distance_thresh: 0.4
map_update_angle_thresh: 0.06
odom_frame: "odom"
