# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: maprequest.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from is_msgs import common_pb2 as is__msgs_dot_common__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='maprequest.proto',
  package='is.robot',
  syntax='proto3',
  serialized_options=_b('\n\014com.is.robotP\001'),
  serialized_pb=_b('\n\x10maprequest.proto\x12\x08is.robot\x1a\x14is_msgs/common.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"<\n\x0eMappingRequest\x12\n\n\x02id\x18\x01 \x01(\x04\x12\x1e\n\x05poses\x18\x02 \x03(\x0b\x32\x0f.is.common.PoseB\x10\n\x0c\x63om.is.robotP\x01\x62\x06proto3')
  ,
  dependencies=[is__msgs_dot_common__pb2.DESCRIPTOR,google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])




_MAPPINGREQUEST = _descriptor.Descriptor(
  name='MappingRequest',
  full_name='is.robot.MappingRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='is.robot.MappingRequest.id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='poses', full_name='is.robot.MappingRequest.poses', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=85,
  serialized_end=145,
)

_MAPPINGREQUEST.fields_by_name['poses'].message_type = is__msgs_dot_common__pb2._POSE
DESCRIPTOR.message_types_by_name['MappingRequest'] = _MAPPINGREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MappingRequest = _reflection.GeneratedProtocolMessageType('MappingRequest', (_message.Message,), dict(
  DESCRIPTOR = _MAPPINGREQUEST,
  __module__ = 'maprequest_pb2'
  # @@protoc_insertion_point(class_scope:is.robot.MappingRequest)
  ))
_sym_db.RegisterMessage(MappingRequest)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
